# Generated by Django 5.2.5 on 2025-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='correlativas',
            field=models.ManyToManyField(blank=True, related_name='materias_dependientes', to='materias.materia'),
        ),
    ]
