# Generated by Django 5.2.5 on 2025-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_correlativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
