# Generated by Django 5.2.5 on 2025-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
