# Generated by Django 5.2.5 on 2025-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
