# Generated by Django 5.2.5 on 2025-08-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('cursando', 'Cursando'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], max_length=20)),
            ],
        ),
    ]
